version: '3'

networks:
  nw:
    driver: bridge

services:
  api42:
    container_name: api42
    build: ./Api42
    command: uvicorn ApiMain.asgi:application --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./Api42:/code
    ports:
      - "8080:8080"
    networks:
      - nw

  chat:
    build: ./Chat
    container_name: chat
    command: uvicorn Chat.asgi:application --host 0.0.0.0 --port 9090 --reload
    volumes:
      - ./Chat:/code
    ports:
      - "9090:9090"
    networks:
      - nw

  backend:
    build: ./backend
    command: uvicorn backend.asgi:application --host 0.0.0.0 --port 9191 --reload
    container_name: backend
    volumes:
      - ./backend:/code
    ports:
      - "9191:9191"
    depends_on:
      - db
    networks:
      - nw

  game:
    build: ./Game
    container_name: game
    command: uvicorn Game.asgi:application --host 0.0.0.0 --port 5050 --reload
    volumes:
      - ./Game:/code
    ports:
      - "5050:5050"
    networks:
      - nw

  nginx:
    build: ./frontend
    container_name: frontend
    command: /bin/sh -c "nginx -g 'daemon off;'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - api42
      - chat
      - backend
      - game
    networks:
      - nw

  db:
    image: postgres:latest
    container_name: db
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    networks:
      - nw

volumes:
  postgres_data: