#!/bin/bash
set -e

psql --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER "$POSTGRES_USER" WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD';
    CREATE DATABASE "$POSTGRES_DB";
    ALTER USER "$POSTGRES_USER" CREATEDB;
    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$POSTGRES_USER";
EOSQL

mv /tmp/postgresql.conf /var/lib/postgresql/data/postgresql.conf
