DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_database WHERE datname = 'backend') THEN
        CREATE DATABASE backend;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_user WHERE usename = 'user1') THEN
        CREATE USER user1 WITH PASSWORD '123';
    END IF;
END
$$;


GRANT ALL PRIVILEGES ON DATABASE backend TO user1;
ALTER ROLE user1 WITH SUPERUSER;
ALTER ROLE user1 WITH CREATEROLE;