# Generated by Django 4.2.10 on 2024-03-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api42', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online_status',
            field=models.BooleanField(default=False, verbose_name='online_status'),
        ),
    ]
