# Generated by Django 4.2.10 on 2024-03-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api42', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/code/media/images/tyler.jpeg', null=True, upload_to='images/', verbose_name='profile picture'),
        ),
    ]
