# Generated by Django 4.2.10 on 2024-03-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api42', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='media/images/tyler.png', upload_to='media/images/', verbose_name='profile picture'),
        ),
    ]
