# Generated by Django 3.2.12 on 2024-03-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api42', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ft_api_registered',
            field=models.BooleanField(default=False, verbose_name='ft_api_registered'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default='tyler.png', max_length=300, verbose_name='profile picture'),
        ),
    ]
