# Generated by Django 4.2.10 on 2024-03-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api42', '0005_auto_20240319_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default='Default Profile Picture.jpg', max_length=300, verbose_name='profile picture'),
        ),
    ]
