# Generated by Django 4.2.10 on 2024-03-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api42', '0006_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default='images/Default Profile Picture.jpg', max_length=300, verbose_name='profile picture'),
        ),
    ]
