# Generated by Django 4.2.10 on 2024-03-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api42', '0007_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(error_messages={'unique': 'A user with that email already exists.'}, max_length=128, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default='Default Profile Picture.jpg', max_length=300, verbose_name='profile picture'),
        ),
    ]
