# Generated by Django 4.2.10 on 2024-03-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api42', '0008_alter_user_email_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(error_messages={'unique': 'A user with that email already exists.'}, max_length=128, verbose_name='email address'),
        ),
    ]
