# Generated by Django 4.2.10 on 2024-03-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api42', '0010_alter_user_password_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
