# Generated by Django 4.2.9 on 2024-03-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('who_win', models.CharField()),
                ('game_type', models.CharField(max_length=255)),
            ],
        ),
    ]
